"Upload failed" = "فشل التحميل";
"pastie.org is unreachable." = "pastie.org لا يمكن الوصول لـ.";
ATTACHMENTS = "مرفقات";
CANNOT_EMAIL = "لا يمكن إرسال البريد الألكتروني من هذا الجهاز.";
CONTACT_AUTHOR = "التواصل مع المطور";
COPY = "نسخ";
DETAIL_REQUIRED_MESSAGE = "يجب عليك إدخال رسالة لإتمام العملية.";
DETAIL_REQUIRED_TITLE = "المدخلات المطلوبة";
EMAIL_FAILED_1 = "فشل في إرسال البريد الإلكتروني.\nخطأ: ";
EMAIL_PLACEHOLDER = "يرجى إدخال التفاصيل هنا، مثل:n/n/ متى بدأت المشكلة ؟n/n/ هل تحدث المشكلة في كل مرة؟";
NOT_TEXT_MESSAGE = "الملف المحدد لا يظهر كملف نصي.n/n/ لا يمكن عرضه من خلال مستعرض النصوص.";
INCLUDE_UNTITLED = "بدون عنوان";
OK = "حسناً";
VIEW_IN_APP_STORE = "عرض التطبيق في متجر البرامج";
VIEW_IN_CYDIA = "عرض التطبيق في السيديا
